using prepAIred.Data;

namespace prepAIred.Services
{
    /// <summary>
    /// Service interface for interacting with AI agents and generating interview questions.
    /// </summary>
    public interface IAIService
    {
        /// <summary>
        /// Sends a prompt to the specified AI agent and retrieves a list of interview responses.
        /// </summary>
        /// <param name="agent">The AI agent to which the prompt will be sent.</param>
        /// <param name="prompt">The text prompt to provide to the AI agent.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains a list of <see
        /// cref="Interview"/> objects generated by the AI agent. The list will be empty if no responses are generated.</returns>
        Task<List<Interview>> AskAiAgentAsync(AIAgent agent, string prompt);
    }
}
